### PR TITLE
Change controls to conform with tw editor

### LINKED ISSUE #10: Use same controls as in the client editor
Instead of space to place tiles use left click. And instead of moving the view with drag use ctrl+drag.

### PR DESCRIPTION
**Pull request by k2d222**
fixed #10

### CODE REVIEW

**Comment by ChillerDragon** [comment]
How does one navigate in the map?

I think the tooltip hint bar from the client editor would also be a nice to have here. Explaining the controls.

**Comment by k2d222** [comment]
it's mouse wheel button to move around but yeah should add ctrl+click as well. Arrow keys too.

**Comment by ChillerDragon** [comment]
> it's mouse wheel button to move around but yeah should add ctrl+click as well. Arrow keys too.

So im rip on laptop touchpad?

**Comment by k2d222** [comment]
yeah you're doomed of course this editor is laptop-racist ;)

**Comment by ChillerDragon** [comment]
faaak

**Comment by ChillerDragon** [comment]
Yea but other than that. Dope pr. LGTM

**Comment by ChillerDragon** [comment]
Works like a charm! Feels so editor like :)

**Pull request merged**
