### PR TITLE
Add statusbar (closed #36)

### LINKED ISSUE #36: Add tooltip bar for control hints
I think the tooltip hint bar from the client editor would also be a nice to have here. Explaining the controls.
Untitled

### PR DESCRIPTION
**Pull request by ChillerDragon**
Yea its not very sophisticated yet..

image

### CODE REVIEW

**Comment by k2d222** [comment]
You quick! but you broke the padding on the top bar buttons!

**Comment by k2d222** [comment]
also, unreleated to this, I see wrapping issues in the left bar, where the 3 dots go on next line on <no name> layers. was that already the case before?

**Comment by ChillerDragon** [comment]
Yea the

```css
* {
  margin: 0;
  padding: 0;
}
```

Might be a bit drastic. Its just always the first thing I do when doing CSS to not get bounced by the body.
I couldn't spot any issues with my eyes tho. Lemme try to fix it.

**Comment by ChillerDragon** [comment]
Does this work?

image

**Comment by k2d222** [comment]
nice

**Pull request merged**
